# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: yolo
  name: yolo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: yolo
  template:
    metadata:
      labels:
        run: yolo
    spec:
      containers:
      - image: vallard/photo-detect
        imagePullPolicy: Always
        name: yolo
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: yolo
  name: yolo
  namespace: default
spec:
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    run: yolo
  sessionAffinity: None
  type: ClusterIP
